name: 🌟 Quantum Index Maintenance

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'INDEX.md'
  
jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          
      - name: Update INDEX.md
        run: |
          python - <<EOF
          import os
          import yaml
          from datetime import datetime
          
          def gather_knowledge():
              sections = {
                  '🌱 seedling': [],
                  '🌲 evergreen': [],
                  '🌊 flux': [],
                  '📱 implementations': []
              }
              
              for root, dirs, files in os.walk('.'):
                  if '.git' in root or '.github' in root:
                      continue
                      
                  for file in files:
                      if file.endswith(('.md', '.mdx')) and file != 'INDEX.md':
                          path = os.path.join(root, file)
                          
                          # Determine section
                          if 'seedling' in path:
                              sections['🌱 seedling'].append(path)
                          elif 'evergreen' in path:
                              sections['🌲 evergreen'].append(path)
                          elif 'flux' in path:
                              sections['🌊 flux'].append(path)
                          elif 'implementations' in path:
                              sections['📱 implementations'].append(path)
                              
              return sections
              
          def create_index(sections):
              content = [
                  '# 🌟 Quantum Mnemos Knowledge Index',
                  f'\n> Last updated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")} UTC\n',
                  '## 🎯 Active Quantum States',
                  '- Current phase exploration',
                  '- Implementation progress tracking',
                  '\n## 📚 Knowledge Crystallization\n'
              ]
              
              for section, files in sections.items():
                  content.append(f'\n### {section}\n')
                  for file in sorted(files):
                      name = os.path.basename(file)[:-3]  # Remove .md
                      link = file.replace(' ', '%20')
                      content.append(f'- [[{name}]]({link})')
                      
              content.extend([
                  '\n## 🌓 Shadow Integration',
                  '- Questions & Uncertainties',
                  '- Evolution Vectors',
                  '- Integration Points',
                  '\n## 🔄 Temporal Markers',
                  f'- Last Indexed: {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")} UTC',
                  '- Current Phase: Initial Implementation',
                  '- Evolution Stage: Quantum Emergence'
              ])
              
              return '\n'.join(content)
              
          sections = gather_knowledge()
          index_content = create_index(sections)
          
          with open('INDEX.md', 'w') as f:
              f.write(index_content)
          EOF
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "🔄 Quantum index synchronization"
          add: "INDEX.md"
          default_author: github_actions